#pragma once
#pragma once
#include <map>
#include <iostream>

    static map<string, string> EN = {
    {"login", "Login"},
    {"MainMenue", "Main Munue"},
    {"ChooseOption", "Choose what do you want to do?"},
    {"PressAnyKey", "Press any key to go back to"},
    {"MainMenu","Main Menu"},
    {"ShowClients", "Show Client List"},
    {"NoClients","No Clients Available In the System"},
    {"ClientListScreen", "Client List Screen"},
    {"AddNewClientScreen", "Add New Client Screen"},
    {"EnterNumClient", "Please Enter client Account Number"},
    {"Ch ooseAnother","Account Number Is Already Used, Choose another one"},
    {"AccountAddSuccess","Account Added Successfully"},
    {"ErrorEmpty","Error account was not saved because it's Empty"},
    {"ErrorAccountUsed","Error account was not saved because account number is used!"},
    {"ClientCard","Client Card"},
    {"ClientName", "Client Name"},
    {"EnterWord", "Enter"},
    {"FirstName", "Firstname"},
    {"LastName", "Last Name"},
    {"Email", "Email"},
    {"Phone", "Phone"},
    {"AccountNumber", "Account Number"},
    {"PinCode", "Pin Code"},
    {"AddClient", "Add New Client"},
    {"DeleteClient", "Delete Client"},
    {"DLTclientScreen","Delete Client Screen"},
    {"AreDLTCl","Are you sure you want to delete this client"},
    {"DLTSucc","Client Deleted Successfully"},
    {"ErrorDLT","Error Client Was not Deleted"},
    {"UpdateClient", "Update Client Info"},
    {"UpdateClientScreen","Update Client Screen"},
    {"UpdatedAccountClient","Account Updated Successfully"},
    {"FindClient", "Find Client"},
    {"FINDCSc","Find Client Screen"},
    {"ClientNotFound","Account number is not found, choose another one "},
    {"ClintFound","Client found"},
    {"Transactions", "Transactions"},
    {"ManageUsers", "Manage Users"},
    {"UsersSCR","Manage Users screen"},
    {"Choose16","Choose what do you want to do? [1 to 6]?"},
    {"Enter16","Enter Number between 1 to 6? "},
    {"GoBackManageMenue","Press any key to go back to Manage Users Menue"},
    {"ManageUSersMenue","Manage Users Menu"},
    {"ListUsers","List Users"},
    {"NewUser","Add New User"},
    {"DLTUser","Delete User"},
    {"UPUser","Update User"},
    {"FIndUser","Find User"},
    {"UsersMenue","Manage Users Menue"},
    {"MainMenue","Main Menue"},
    {"UserList","User List Screen"},
    {"User-s","User(s)"},
    {"UserName","UserName"},
    {"FullName","Full Name"},
    {"Password","Password"},
    {"Permissions","Permissions"},
    {"fff","Access Denied! Contact your Admin."},
    {"NoUsers","No Users Available In the System!"},
    {"UserCard","User Card"},
    {"FullAccessQST","Do you want to give full access?"},
    {"AccessQST","Do you want to give access to : "},
    {"ShowList","Show Client List?"},
    {"NewUserScreen","Add New User Screen"},
    {"EnterUser","Please Enter UserName"},
    {"UsernameUsed","UserName Is Already Used, Choose another one"},
    {"UserAddes","User Addeded Successfully"},
    {"AccessDenied","Access Denied! Contact your Admin."},
    {"ErrorUserEmpty","Error User was not saved because it's Empty"},
    {"ErrorUserUsed","Error User was not saved because UserName is used"},
    {"updatethisUser","Are you sure you want to update this User"},
    {"UpdateUserInfo","Update User Info"},
    {"UserUpSucces","User Updated Successfully"},
    {"ErrorEmptyU","Error User was not saved because it's Empty"},
    {"FUScreen","Find User Screen"},
    {"UserF","User Found"},
    {"UserNotF","User Was not Found"},
    {"DUSCREEN","Delete User Screen"},
    {"UserNOTF","User is not found, choose another one"},
    {"DleteThisUserQST","Are you sure you want to delete this User"},
    {"UDSucces","User Deleted Successfully"},
    {"ErrorDU","Error User Was not Deleted"},
    {"LoginScreen","Login Screen"},
    {"InvalisUP","Invlaid Username/Password!"},
    {"EUser","Enter Username?"},
    {"EPass","Enter Password?"},
    {"Logout", "Logout"},
    {"withdraw", "Withdraw Money"},
    {"deposit", "Deposit Money"},
    {"balance", "Account Balance"},
    {"exit", "Exit"},
    {"welcome", "Welcome to the Bank System"},
    {"UserEX1","User"},
    {"DateEX1","Date"},
    {"YH","You have"},
    {"TrialsLogin","Trial(s) to login."},
    {"FailedTrials","Your are Locked after 3 faild trails"},
    {"LoginLogoutRegister","Login Logout Register"},
    {"LoginLogoutRegisterS","Login Logout Register Screen"},
    {"DateTime","Date & Time"},
    {"TransferScreen","Transfer Screen"},
    { "EnterAccountToTransferFrom","Please enter account number to transfer from" },
    { "EnterAccountToTransferTo","Please enter account number to transfer to" },
    { "EnterTransferAmount","Enter transfer Amount" },
    { "AmountExceedsBalance","Amount exceeds the available balance, enter another amount" },
    { "ConfirmOperation","Are you sure you want to perform this operation?" },
    { "TransferSuccess","Transfer done successfully" },
    { "TransferFailed","Transfer Failed" },
    { "TransactionScreen","Transaction Screen" },
    { "TransactionMenu","Transaction Menu" },
    { "Deposit","Deposit" },
    { "Withdraw","Withdraw" },
    { "TotalBalances","Total Balances" },
    { "Transfer","Transfer" },
    { "MainMenu","Main Menu" },
    { "BackToTransactionMenu","Press any key to go back to Transaction Menu..." },
    { "TransferLog","Transfer Log" },
    { "SourceAccount","Source Account" },
    { "DestinationAccount","Destination Account" },
    { "Amount","Amount" },
    { "SourceBalance","Source Balance" },
    { "DestinationBalance","Destination Balance" },
    { "User","User" },
};



