#pragma once
#include <map>
#include <iostream>


using namespace std;

static map<string, string> FR = {
    {"login", "Connexion"},
    {"LoginScreen", "Ecran de connexion"},
    {"InvalisUP", "Nom d'utilisateur ou mot de passe invalide !"},
    {"EUser", "Entrez le nom d'utilisateur ?"},
    {"EPass", "Entrez le mot de passe ?"},
    {"ChooseOption", "Veuillez choisir une option"},
    {"PressAnyKey", "Appuyez sur une touche pour revenir au "},
    {"MainMenu","Main menu principal"},
    {"ShowClients", "Afficher la liste des clients"},
    {"NoClients","Il n'y a aucun client enregistré dans le système"},
    {"ClientListScreen", "Liste des clients"},
    {"AddNewClientScreen", "Ecran de creation d'un client"},
    {"EnterNumClient", "Entrez le numero de compte du client"},
    {"ChooseAnother","Le numéro de compte est déjà utilisé, veuillez en choisir un autre"},
    {"AccountAddSuccess","Compte ajouté avec succès"},
    {"ErrorEmpty","Erreur : le compte n'a pas été enregistré car il est vide"},
    {"ErrorAccountUsed","Erreur : le compte n'a pas été enregistré car le numéro de compte est déjà utilisé !"},
    {"ClientCard","Fiche client"},
    {"EnterWord", "Entrez"},
    {"FirstName", "le prénom"},
    {"LastName", "Nom de famille"},
    {"Email", "Email"},
    {"Phone", "Téléphone"},
    {"AccountNumber", "Numéro de compte"},
    {"PinCode", "Code PIN"},
    {"balance", "Solde"},
    {"AddClient", "Ajouter un nouveau client"},
    {"DeleteClient", "Supprimer un client"},
    {"DLTclientScreen","Écran de suppression du client"},
    {"AreDLTCl","Êtes-vous sûr de vouloir supprimer ce client"},
    {"DLTSucc","Client supprimé avec succès"},
    {"ErrorDLT","Erreur : le client n'a pas été supprimé"},
    {"UpdateClient", "Mettre à jour les informations du client"},
    {"UpdateClientScreen", "Écran de mise à jour du client"},
    {"UpdatedAccountClient", "Compte mis à jour avec succès"},
    {"FindClient", "Rechercher un client"},
    {"FINDCSc","Écran de recherche du client"},
    {"ClientNotFound","Numéro de compte introuvable, veuillez en choisir un autre "},
    {"ClintFound","Client trouvé"},
    {"Transactions", "Transactions"},
    {"ManageUsers", "Gestion des utilisateurs"},
    {"UsersSCR","Écran de gestion des utilisateurs"},
    {"Choose16","Choisissez ce que vous voulez faire ? [1 à 6]"},
    {"Enter16","Entrez un numéro entre 1 et 6 "},
    {"GoBackManageMenue", "Appuyez sur une touche pour revenir au menu de gestion des utilisateurs"},
    {"ManageUSersMenue", "Menu de gestion des utilisateurs"},
    {"ListUsers", "Lister les utilisateurs"},
    {"NewUser", "Ajouter un nouvel utilisateur"},
    {"DLTUser", "Supprimer un utilisateur"},
    {"UPUser", "Mettre à jour un utilisateur"},
    {"FIndUser", "Rechercher un utilisateur"},
    {"UsersMenue", "Menu de gestion des utilisateurs"},
    {"MainMenue", "Menu principal"},
    {"UserList", "Écran de la liste des utilisateurs"},
    {"User-s", "Utilisateur(s)"},
    {"UserName", "Nom d'utilisateur"},
    {"FullName", "Nom complet"},
    {"Password", "Mot de passe"},
    {"Permissions", "Permissions"},
    {"AccessDenied","Accès refusé ! Contactez votre administrateur."},
    {"NoUsers", "Aucun utilisateur disponible dans le système !"},
    {"UserCard", "Fiche utilisateur"},
    {"FullAccessQST", "Voulez-vous accorder un accès complet ?"},
    {"AccessQST", "Voulez-vous accorder l'accès à : "},
    {"ShowList", "Afficher la liste des clients ?"},
    {"NewUserScreen", "Écran d'ajout d'un nouvel utilisateur"},
    {"EnterUser", "Veuillez saisir le nom d'utilisateur"},
    {"UsernameUsed", "Le nom d'utilisateur est déjà utilisé, veuillez en choisir un autre"},
    {"UserAddes", "Utilisateur ajouté avec succès"},
    {"ErrorUserEmpty", "Erreur : l'utilisateur n'a pas été enregistré car il est vide"},
    {"ErrorUserUsed", "Erreur : l'utilisateur n'a pas été enregistré car le nom d'utilisateur est déjà utilisé"},
    {"updatethisUser", "Êtes-vous sûr de vouloir mettre à jour cet utilisateur ?"},
    {"UpdateUserInfo", "Mise à jour des informations de l'utilisateur"},
    {"UserUpSucces", "Utilisateur mis à jour avec succès"},
    {"ErrorEmptyU", "Erreur : l'utilisateur n'a pas été enregistré car il est vide"},
    {"Logout", "Déconnexion"},
    {"MainMenue", "Menu Principal"},
    {"withdraw", "Retirer de l'argent"},
    {"deposit", "Deposer de l'argent"},
    {"balance", "Solde du compte"},
    {"DUSCREEN", "Écran de suppression de l'utilisateur"},
    {"UserNOTF", "Utilisateur introuvable, veuillez en choisir un autre"},
    {"DleteThisUserQST", "Êtes-vous sûr de vouloir supprimer cet utilisateur ?"},
    {"UDSucces", "Utilisateur supprimé avec succès"},
    {"ErrorDU", "Erreur : l'utilisateur n'a pas été supprimé"},
    {"FUScreen", "Écran de recherche de l'utilisateur"},
    {"UserF", "Utilisateur trouvé"},
    {"UserNotF", "Utilisateur introuvable"},
    {"exit", "Quitter"},
    {"welcome", "Bienvenue dans le système bancaire"},
    {"UserEX1","Utilisateur"},
    {"DateEX1","Date"},
    {"YH","Il vous reste"},
    {"TrialsLogin","tentative(s) de connexion."},
    {"FailedTrials","Votre compte est bloqué après 3 tentatives de connexion échouées"},
    {"LoginLogoutRegister","Journal de connexion et de déconnexion" },
    {"LoginLogoutRegisterS","Ecran du Journal de connexion et de déconnexion" },
    {"DateTime","Date et heure"},
    {"TransferScreen","Ecran de transfert"},
    {"EnterAccountToTransferFrom","Veuillez entrer le numéro de compte source"},
    {"EnterAccountToTransferTo","Veuillez entrer le numéro de compte destinataire" },
    {"EnterTransferAmount", "Entrez le montant du transfert" },
    {"AmountExceedsBalance","Le montant dépasse le solde disponible, entrez un autre montant" },
    {"ConfirmOperation","Etes-vous sûr de vouloir effectuer cette opération ?" },
    {"TransferSuccess","Transfert effectué avec succès" },
    {"TransferFailed","Echec du transfert" },
    {"TransactionScreen","Ecran des transactions" },
    {"TransactionMenu","Menu des transactions" },
    {"Deposit","Dépôt" },
    {"Withdraw","Retrait" },
    {"TotalBalances","Total des soldes" },
    {"Transfer","Transfert" },
    {"MainMenu","Menu principal" },
    {"BackToTransactionMenu","Appuyez sur une touche pour revenir au menu des transactions..." },
    {"TransferLog","Journal des transferts" },
    { "SourceAccount","Compte source" },
    { "DestinationAccount","Compte destinataire" },
    { "Amount","Montant" },
    { "SourceBalance","Solde du compte source" },
    { "DestinationBalance","Solde du compte destinataire" },
    { "User","Utilisateur" },
    { "CurrencyExchange","Change de devises" },
    { "ListCurrencies","Liste des devises" },
    { "FindCurrency","Rechercher une devise" },
    { "UpdateRate","Mettre à jour le taux" },
    { "CurrencyCalculator","Calculateur de devises" },
    { "CurrencyExchangeMainScreen","Ecran principal du change de devises" },
    { "CurrencyExchangeMenu","Menu de change de devises" },
    { "Country","Pays" },
    { "CurrencyCode","Code de devise" },
    { "Rate","Taux de change" },
    { "CurrenciesListScreen","Ecran de la liste des devises" },
    { "Currencies","Devise(s)" },
    { "CurrencyName","Nom de la devise" },
    { "BackToCurrenciesMenu","Appuyez sur une touche pour revenir au menu des devises..." },
    { "FindCurrencyScreen","Ecran de recherche de devise" },
    { "FindBy","Rechercher par : [1] Code ou [2] Pays ?" },
    { "EnterCurrencyCode","Veuillez entrer le code de la devise ?" },
    { "EnterCountryName","Veuillez entrer le nom du pays ?" },
    { "CurrencyFound","Devise trouvée" },
    { "CurrencyCard","Carte de la devise" },
    { "CurrencyNotFound","Devise non trouvée" },
    { "UpdateCurrencyRateScreen","Update Currency Rate Screen" },
    { "ConfirmUpdateRate","Etes-vous sûr de vouloir mettre à jour le taux de cette devise ? o/n" },
    { "EnterNewRate","Veuillez entrer le nouveau taux ?" },
    { "RateUpdateSuccess","Taux de la devise mis à jour avec succès" },

};

